language: perl
perl:
  - "5.22"
  - "5.14"
  - "5.8"
before_install: git submodule update --init
install: "make test-deps"
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "irc.suikawiki.org#mechanize"
    use_notice: true
env:
  global:
    secure: "ml4T+GrDy83W40TWbWwTAaflIbCTb0Eyq6lZgv6eN86bvckF09N8QntevqU5/PxuW+jczKjib0fnyrhjh8Ib44W74owuKOCZbVvLQSE1SmG75lmjfdJC9FvQNdGyj24tj7jVMl67ALBITsDcSd/fC6dxoe7h6CESVkMDf8P3CU0="
after_success:
  - curl -s -S -L https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
